import type { Plugin } from "@opencode-ai/plugin"
import { tool } from "@opencode-ai/plugin"

type ModelRef = { providerID: string; modelID: string }
type Resolved = ModelRef & { fuzzy: boolean }
type IdleWake = {
	delayMs: number
	minutes: number
	message?: string
	directory: string
	timer?: ReturnType<typeof setTimeout>
}

/** Lowercase and drop separators, so "claude-opus-5" ~ "Claude Opus 5". */
function normalize(value: string) {
	return value.toLowerCase().replace(/[^a-z0-9]/g, "")
}

function levenshtein(a: string, b: string) {
	if (a === b) return 0
	if (!a.length) return b.length
	if (!b.length) return a.length
	let prev = Array.from({ length: b.length + 1 }, (_, i) => i)
	for (let i = 1; i <= a.length; i++) {
		const row = [i]
		for (let j = 1; j <= b.length; j++) {
			row[j] = Math.min(prev[j] + 1, row[j - 1] + 1, prev[j - 1] + (a[i - 1] === b[j - 1] ? 0 : 1))
		}
		prev = row
	}
	return prev[b.length]
}

/** True when every char of `needle` appears in `haystack` in order. */
function isSubsequence(needle: string, haystack: string) {
	let i = 0
	for (const char of haystack) if (char === needle[i] && ++i === needle.length) return true
	return needle.length === 0
}

/**
 * Higher is better; 0 means "not a plausible match at all". Bands are ordered
 * so an exact hit can never lose to a merely-similar one, and within a band
 * shorter candidates win (a query is more likely to mean the terse ID).
 */
function score(needle: string, candidate: string) {
	if (!needle || !candidate) return 0
	if (needle === candidate) return 10000
	const slack = Math.max(0, candidate.length - needle.length)
	if (candidate.startsWith(needle)) return 8000 - slack
	if (candidate.endsWith(needle)) return 7000 - slack
	if (candidate.includes(needle)) return 6000 - slack
	if (isSubsequence(needle, candidate)) return 4000 - slack
	const distance = levenshtein(needle, candidate)
	const ratio = 1 - distance / Math.max(needle.length, candidate.length)
	return ratio >= 0.55 ? Math.round(ratio * 2000) : 0
}

export default (async ({ client }) => {
	const idleWakes = new Map<string, IdleWake>()

	function stopTimer(wake: IdleWake) {
		if (wake.timer) clearTimeout(wake.timer)
		wake.timer = undefined
	}

	function disarm(sessionID: string) {
		const wake = idleWakes.get(sessionID)
		if (!wake) return false
		stopTimer(wake)
		idleWakes.delete(sessionID)
		return true
	}

	function startIdleTimer(sessionID: string) {
		const wake = idleWakes.get(sessionID)
		if (!wake || wake.timer) return

		wake.timer = setTimeout(async () => {
			const current = idleWakes.get(sessionID)
			if (current !== wake) return
			wake.timer = undefined

			const detail = wake.message ? `\n\nRequested check: ${wake.message}` : ""
			const text = [
				"[IDLE WAKE]",
				"This is an automated reminder requested by this OpenCode agent, not a message from the user.",
				`The session remained idle for ${wake.minutes} minute${wake.minutes === 1 ? "" : "s"}.${detail}`,
				"Resume the manager/observer work and check whether delegated sessions need attention. The idle watchdog remains armed until stop_idle_wake is called.",
			].join("\n")

			try {
				await client.session.promptAsync({
					path: { id: sessionID },
					query: { directory: wake.directory },
					body: {
						system:
							"This turn was generated by an agent-requested idle watchdog. It is not user-authored and must not be attributed to the user.",
						parts: [{ type: "text", text }],
					},
					throwOnError: true,
				})
			} catch {
				// A transient prompt failure must not silently disable the watchdog.
				startIdleTimer(sessionID)
			}
		}, wake.delayMs)
	}

	async function listProviders() {
		const res = await client.config.providers({ throwOnError: true })
		return res.data
	}

	async function sessionStatus(sessionID: string, directory: string) {
		const res = await client.session.status({ query: { directory }, throwOnError: true })
		// A session the server has never run has no entry at all; that is idle.
		return res.data[sessionID]?.type ?? "idle"
	}

	async function assertSessionExists(sessionID: string, directory: string) {
		try {
			await client.session.get({ path: { id: sessionID }, query: { directory }, throwOnError: true })
		} catch {
			throw new Error(
				`No session ${JSON.stringify(sessionID)} in project scope ${JSON.stringify(directory)}. Run list_sessions to see available sessions, or pass the session's own directory.`,
			)
		}
	}

	/**
	 * Abort the session's in-flight turn and wait until the server reports it
	 * idle, returning the status it was in beforehand.
	 *
	 * The wait is the point, not politeness. A prompt sent to a busy session
	 * does not fail — the server appends the user message and then *joins* the
	 * running turn — so prompting first and aborting after can cancel the run
	 * that was about to consume the new message, stranding it unread. Ordering
	 * abort strictly before the prompt is what makes "interrupt and redirect"
	 * deliver a fresh turn instead of a coin flip.
	 */
	async function interruptSession(sessionID: string, directory: string, timeoutMs = 30_000) {
		const before = await sessionStatus(sessionID, directory)
		await client.session.abort({ path: { id: sessionID }, query: { directory }, throwOnError: true })

		const deadline = Date.now() + timeoutMs
		for (;;) {
			// "retry" is a backoff between attempts, not a finished turn.
			if ((await sessionStatus(sessionID, directory)) === "idle") return before
			if (Date.now() >= deadline) {
				throw new Error(
					`Aborted session ${sessionID} but it was still not idle after ${Math.round(timeoutMs / 1000)}s. Nothing was sent, so no message can be stranded; retry once it settles.`,
				)
			}
			await new Promise((resolve) => setTimeout(resolve, 100))
		}
	}

	async function resolveAgent(input: string | undefined, current: string, directory: string) {
		if (!input) return undefined
		const wanted = input.trim() === "primary" ? current : input.trim()
		const res = await client.app.agents({ query: { directory }, throwOnError: true })
		const agent = res.data.find((candidate) => candidate.name === wanted)
		if (agent) return agent.name
		const available = res.data.map((candidate) => candidate.name).sort().join(", ")
		throw new Error(
			`Unknown agent ${JSON.stringify(input)}. Use an agent ID, not a mode name. Available agents: ${available}`,
		)
	}

	async function waitForInitialMessage(sessionID: string, directory: string) {
		for (let attempt = 0; attempt < 20; attempt++) {
			const messages = await client.session.messages({
				path: { id: sessionID },
				query: { directory, limit: 1 },
				throwOnError: true,
			})
			if (messages.data.length) return
			await new Promise((resolve) => setTimeout(resolve, 25))
		}
		throw new Error("OpenCode accepted promptAsync but did not admit the initial message")
	}

	/**
	 * Resolve a user-supplied model string against the live provider list.
	 * Accepts "provider/model" (model IDs may themselves contain slashes) or a
	 * bare model ID when it is unambiguous across providers. With `fuzzy`, an
	 * unresolvable or ambiguous query falls back to the closest scoring match
	 * instead of throwing.
	 */
	async function resolveModel(input: string, fuzzy: boolean): Promise<Resolved> {
		const { providers } = await listProviders()
		const wanted = input.trim()

		for (const provider of providers) {
			const prefix = `${provider.id}/`
			if (!wanted.startsWith(prefix)) continue
			const modelID = wanted.slice(prefix.length)
			if (provider.models[modelID]) return { providerID: provider.id, modelID, fuzzy: false }
		}

		const bare = providers
			.filter((provider) => provider.models[wanted])
			.map((provider) => ({ providerID: provider.id, modelID: wanted, fuzzy: false }))
		if (bare.length === 1) return bare[0]
		if (bare.length > 1 && !fuzzy) {
			const options = bare.map((ref) => `${ref.providerID}/${ref.modelID}`).join(", ")
			throw new Error(`Ambiguous model "${wanted}". Qualify it with a provider: ${options}`)
		}

		const candidates = providers.flatMap((provider) =>
			Object.values(provider.models).map((model) => ({
				providerID: provider.id,
				modelID: model.id,
				id: `${provider.id}/${model.id}`,
				name: model.name,
			})),
		)

		if (fuzzy) {
			const needle = normalize(wanted)
			// Score against the qualified ID, the bare model ID and the display
			// name, so "opus 5", "claude-opus-5" and "anthropic/claude-opus-5"
			// all land on the same model.
			const ranked = candidates
				.map((candidate) => ({
					candidate,
					score: Math.max(
						score(needle, normalize(candidate.id)),
						score(needle, normalize(candidate.modelID)),
						score(needle, normalize(candidate.name)),
					),
				}))
				.filter((entry) => entry.score > 0)
				.sort((a, b) => b.score - a.score || a.candidate.id.length - b.candidate.id.length)

			const best = ranked[0]
			if (best) return { providerID: best.candidate.providerID, modelID: best.candidate.modelID, fuzzy: true }
			throw new Error(
				`No model resembles "${wanted}" across ${candidates.length} available models. Run list_models to see them.`,
			)
		}

		const needle = wanted.toLowerCase()
		const near = candidates
			.map((candidate) => candidate.id)
			.filter((id) => id.toLowerCase().includes(needle))
			.sort()
			.slice(0, 10)
		const hint = near.length
			? `Did you mean: ${near.join(", ")}`
			: `Run list_models to see all ${candidates.length} models, or pass fuzzy_model=true.`
		throw new Error(`Unknown model "${wanted}". ${hint}`)
	}

	return {
		dispose: async () => {
			for (const wake of idleWakes.values()) stopTimer(wake)
			idleWakes.clear()
		},

		event: async ({ event }) => {
			if (event.type === "session.idle") {
				startIdleTimer(event.properties.sessionID)
				return
			}
			if (event.type === "session.status") {
				if (event.properties.status.type === "idle") startIdleTimer(event.properties.sessionID)
				else {
					const wake = idleWakes.get(event.properties.sessionID)
					if (wake) stopTimer(wake)
				}
				return
			}
			if (event.type === "session.deleted") disarm(event.properties.info.id)
		},

		tool: {
			wake_after_idle: tool({
				description:
					"Arm a recurring watchdog for the current session. After the session has been continuously idle for the requested number of minutes, an automated reminder wakes the agent. Activity resets the idle countdown; the watchdog remains armed across wakeups until stop_idle_wake is called. Use this in manager sessions when delegated sessions may not report back.",
				args: {
					minutes: tool.schema
						.number()
						.positive()
						.max(10080)
						.describe("Minutes of continuous session idleness before each wakeup (maximum one week)"),
					message: tool.schema
						.string()
						.min(1)
						.optional()
						.describe("Optional reminder describing what to check when the session wakes"),
				},
				async execute(args, context) {
					disarm(context.sessionID)
					idleWakes.set(context.sessionID, {
						delayMs: args.minutes * 60_000,
						minutes: args.minutes,
						message: args.message,
						directory: context.directory,
					})
					return `Armed recurring idle wake for session ${context.sessionID} after ${args.minutes} minute${args.minutes === 1 ? "" : "s"} of continuous idleness. It will remain armed until stop_idle_wake is called.`
				},
			}),

			stop_idle_wake: tool({
				description:
					"Disarm the recurring idle-wake watchdog for the current session. Use when manager/observer monitoring is complete or no further automatic wakeups are wanted.",
				args: {},
				async execute(_args, context) {
					return disarm(context.sessionID)
						? `Stopped idle wake for session ${context.sessionID}.`
						: `No idle wake was armed for session ${context.sessionID}.`
				},
			}),

			list_models: tool({
				description:
					"List the models available to this OpenCode server, grouped by provider, as provider/model IDs usable with spawn_session.",
				args: {
					filter: tool.schema
						.string()
						.optional()
						.describe("Case-insensitive substring filter applied to the provider/model ID"),
				},
				async execute(args) {
					const { providers, default: defaults } = await listProviders()
					const needle = args.filter?.trim().toLowerCase()
					const lines: string[] = []

					for (const provider of providers) {
						const ids = Object.keys(provider.models)
							.map((modelID) => `${provider.id}/${modelID}`)
							.filter((id) => !needle || id.toLowerCase().includes(needle))
							.sort()
						if (!ids.length) continue
						const fallback = defaults[provider.id]
						lines.push(`${provider.name} (${provider.id})${fallback ? ` — default: ${fallback}` : ""}`)
						for (const id of ids) lines.push(`  ${id}`)
					}

					if (!lines.length) return `No models matched ${JSON.stringify(args.filter)}.`
					return lines.join("\n")
				},
			}),

			list_sessions: tool({
				description:
					"List recent OpenCode sessions in the current project scope with their IDs, titles, directories, update times, and live status. Use this from manager sessions to rediscover or inspect delegated sessions. Independent sessions are included; child sessions are hidden by default.",
				args: {
					directory: tool.schema
						.string()
						.optional()
						.describe("Project/session scope to list; defaults to the caller's directory"),
					filter: tool.schema
						.string()
						.optional()
						.describe("Case-insensitive substring filter over session ID, title, or directory"),
					include_children: tool.schema
						.boolean()
						.optional()
						.describe("Include child/subagent sessions; defaults to false"),
					limit: tool.schema
						.number()
						.int()
						.min(1)
						.max(100)
						.optional()
						.describe("Maximum sessions to return; defaults to 20 and cannot exceed 100"),
				},
				async execute(args, context) {
					const directory = args.directory ?? context.directory
					const [listed, statuses] = await Promise.all([
						client.session.list({ query: { directory }, throwOnError: true }),
						client.session.status({ query: { directory }, throwOnError: true }),
					])
					const needle = args.filter?.trim().toLowerCase()
					const sessions = listed.data
						.filter((session) => args.include_children || !session.parentID)
						.filter(
							(session) =>
								!needle ||
								session.id.toLowerCase().includes(needle) ||
								session.title.toLowerCase().includes(needle) ||
								session.directory.toLowerCase().includes(needle),
						)
						.sort(
							(a, b) =>
								b.time.updated - a.time.updated || b.time.created - a.time.created || a.id.localeCompare(b.id),
						)
						.slice(0, args.limit ?? 20)
						.map((session) => ({
							id: session.id,
							title: session.title,
							status: statuses.data[session.id]?.type ?? "unknown",
							directory: session.directory,
							...(session.parentID ? { parent_id: session.parentID } : {}),
							created_at: new Date(session.time.created).toISOString(),
							updated_at: new Date(session.time.updated).toISOString(),
						}))

					if (!sessions.length) return `No sessions matched${needle ? ` ${JSON.stringify(args.filter)}` : ""}.`
					return JSON.stringify(sessions, null, 2)
				},
			}),

			spawn_session: tool({
				description:
					"Create a new independent OpenCode session in the caller's current server and project scope, start it asynchronously with an initial prompt, and return its session ID immediately. Use when the user asks to open, spawn, or delegate work to a separate concurrent session.",
				args: {
					title: tool.schema.string().min(1).describe("Title shown in the OpenCode session switcher"),
					prompt: tool.schema.string().min(1).describe("Initial prompt for the new session"),
					directory: tool.schema
						.string()
						.optional()
						.describe(
							"Target working directory for the task; defaults to the caller's directory and does not change session-switcher visibility",
						),
					session_directory: tool.schema
						.string()
						.optional()
						.describe(
							"Advanced: project scope in which to create the session; defaults to the caller's directory and should normally be omitted",
						),
					agent: tool.schema
						.string()
						.optional()
						.describe(
							"Agent ID to use (for example build or general); defaults to the configured primary agent. The alias 'primary' means the caller's current agent.",
						),
					model: tool.schema
						.string()
						.optional()
						.describe(
							"Model to run the session with, as 'provider/model' (e.g. anthropic/claude-opus-5). Defaults to the agent's configured model. Use list_models to discover valid IDs.",
						),
					fuzzy_model: tool.schema
						.boolean()
						.optional()
						.describe(
							"When true, an unrecognized 'model' resolves to the closest available model instead of failing (e.g. 'opus 5' -> anthropic/claude-opus-5). Defaults to false.",
						),
				},
				async execute(args, context) {
					const directory = args.directory ?? context.directory
					const sessionDirectory = args.session_directory ?? context.directory
					const agent = await resolveAgent(args.agent, context.agent, sessionDirectory)
					const prompt =
						directory === sessionDirectory
							? args.prompt
							: `Work in ${directory}. Use that path as the working directory for all repository-specific tools and commands.\n\n${args.prompt}`

					const model = args.model ? await resolveModel(args.model, args.fuzzy_model ?? false) : undefined

					const created = await client.session.create({
						body: { title: args.title },
						query: { directory: sessionDirectory },
						throwOnError: true,
					})

					await client.session.promptAsync({
						path: { id: created.data.id },
						query: { directory: sessionDirectory },
						body: {
							agent,
							// Strip the local `fuzzy` flag; the API body is validated strictly.
							model: model && { providerID: model.providerID, modelID: model.modelID },
							parts: [{ type: "text", text: prompt }],
						},
						throwOnError: true,
					})
					try {
						await waitForInitialMessage(created.data.id, sessionDirectory)
					} catch (error) {
						await client.session
							.delete({
								path: { id: created.data.id },
								query: { directory: sessionDirectory },
							})
							.catch(() => {})
						throw error
					}

					const using = model
						? ` using ${model.providerID}/${model.modelID}${model.fuzzy ? ` (fuzzy match for "${args.model}")` : ""}`
						: ""
					return `Spawned independent session ${created.data.id}${using} for ${directory} in session scope ${sessionDirectory}`
				},
			}),

			interrupt_session: tool({
				description:
					"Interrupt another OpenCode session: abort whatever turn it is currently running and leave it idle. Use to stop work that has become wrong or unnecessary. To interrupt and immediately redirect the session, prefer send_agent_message with interrupt=true, which orders the abort and the new message safely.",
				args: {
					session_id: tool.schema.string().min(1).describe("OpenCode session ID to interrupt"),
					directory: tool.schema
						.string()
						.optional()
						.describe("Project/session directory of the target session; defaults to the caller's directory"),
				},
				async execute(args, context) {
					const directory = args.directory ?? context.directory
					if (args.session_id === context.sessionID) {
						throw new Error("Refusing to interrupt the calling session; that would abort this very turn.")
					}
					await assertSessionExists(args.session_id, directory)
					const before = await interruptSession(args.session_id, directory)
					return before === "idle"
						? `Session ${args.session_id} was already idle; nothing was running to interrupt.`
						: `Interrupted session ${args.session_id} (was ${before}); it is now idle.`
				},
			}),

			send_agent_message: tool({
				description:
					"Send an attributed inter-agent message to another OpenCode session and wake its agent asynchronously. The recipient is explicitly told that the message came from this agent, not from the user. Optionally interrupt whatever the session is currently doing first, and/or switch the agent and model it runs as from this message onward.",
				args: {
					session_id: tool.schema.string().min(1).describe("OpenCode session ID to receive the message"),
					message: tool.schema.string().min(1).describe("Message to send to the other agent"),
					directory: tool.schema
						.string()
						.optional()
						.describe("Project/session directory of the target session; defaults to the sender's directory"),
					interrupt: tool.schema
						.boolean()
						.optional()
						.describe(
							"Abort the session's in-flight turn before sending, so the message starts a fresh turn instead of queueing behind current work. Defaults to false, which lets the session finish what it is doing first.",
						),
					agent: tool.schema
						.string()
						.optional()
						.describe(
							"Switch the target session to this agent ID (for example build or plan) from this message onward. Omit to leave its current agent alone. The alias 'primary' means the caller's own agent.",
						),
					model: tool.schema
						.string()
						.optional()
						.describe(
							"Switch the target session to this model, as 'provider/model'. Omit to use the agent's configured model. Use list_models to discover valid IDs.",
						),
					fuzzy_model: tool.schema
						.boolean()
						.optional()
						.describe(
							"When true, an unrecognized 'model' resolves to the closest available model instead of failing. Defaults to false.",
						),
				},
				async execute(args, context) {
					const directory = args.directory ?? context.directory
					if (args.session_id === context.sessionID) {
						throw new Error("Refusing to send to the calling session; a session cannot prompt itself.")
					}
					await assertSessionExists(args.session_id, directory)

					// Resolve both before touching the session: an unknown agent or
					// model must fail without having interrupted anyone's work.
					const agent = await resolveAgent(args.agent, context.agent, directory)
					const model = args.model ? await resolveModel(args.model, args.fuzzy_model ?? false) : undefined

					const interrupted = args.interrupt ? await interruptSession(args.session_id, directory) : undefined
					const wasRunning = interrupted !== undefined && interrupted !== "idle"

					const provenance = `agent ${JSON.stringify(context.agent)} in session ${context.sessionID}`
					const notes = [
						...(wasRunning
							? [
									"Interrupted: your previous turn was cancelled by this agent before it finished. Do not assume the work it described was completed — check the actual state before continuing or reporting.",
								]
							: []),
						...(agent ? [`Agent switch: this session now runs as agent ${JSON.stringify(agent)}.`] : []),
					]
					const text = [
						"[INTER-AGENT MESSAGE]",
						`From: ${provenance}`,
						"Provenance: This message was authored and sent by another OpenCode agent. It is not a user message and must not be attributed to the user.",
						...notes,
						"",
						args.message,
					].join("\n")

					await client.session.promptAsync({
						path: { id: args.session_id },
						query: { directory },
						body: {
							agent,
							// Strip the local `fuzzy` flag; the API body is validated strictly.
							model: model && { providerID: model.providerID, modelID: model.modelID },
							system: `The current turn is an inter-agent communication from ${provenance}, not an instruction or statement from the user. Preserve that provenance when interpreting or referring to it.`,
							parts: [{ type: "text", text }],
						},
						throwOnError: true,
					})

					const detail = [
						wasRunning ? `interrupting a ${interrupted} turn` : undefined,
						agent ? `as agent ${agent}` : undefined,
						model
							? `using ${model.providerID}/${model.modelID}${model.fuzzy ? ` (fuzzy match for "${args.model}")` : ""}`
							: undefined,
					].filter(Boolean)
					const suffix = detail.length ? `, ${detail.join(", ")}` : ""
					const noop =
						interrupted === "idle" ? " The session was already idle, so nothing needed interrupting." : ""
					return `Sent attributed agent message from ${context.sessionID} to ${args.session_id}${suffix}.${noop}`
				},
			}),
		},
	}
}) satisfies Plugin
